### ISSUE TITLE
Dependency [kanaka/instaparse "1.4.9.3"] could not find artifact

### ISSUE THREAD

**Issue by norton-at-kpmg** [kanaka/instacheck#1]
The following error is raised by kanaka/instacheck {:mvn/version "0.9.1"}.

`Error building classpath. Could not find artifact kanaka:instaparse:jar:1.4.9.3 in central (https://repo1.maven.org/maven2/)`

;; Patched version (retain comments, parse path log)
[kanaka/instaparse "1.4.9.3"]

Is it possible to push this version to the maven repository?

Thank you.

**Comment by kanaka** [comment]
Huh, I thought I had pushed that but apparently not. It should be pushed now.

**Comment by kanaka** [comment]
@kpmg-jp-jnorton BTW, this reminded me that I had an instacheck fix that I hadn't pushed out relating to weight calculations for recursive definitions. I pushed out instacheck 0.9.2 that has the fix.

**Comment by norton-at-kpmg** [comment]
@kanaka Thank you but I'm still facing the same problem - any ideas?

`~/tmp/instacheck   master  git describe --always --long
ba2095f

 ~/tmp/instacheck   master  lein test
Could not find artifact kanaka:instaparse:jar:1.4.9.3 in central (https://repo1.maven.org/maven2/)
Could not find artifact kanaka:instaparse:jar:1.4.9.3 in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
`

**Comment by kanaka** [comment]
I pushed it and instaparse version 1.4.9.3 does appear to be there in the web interface: https://clojars.org/kanaka/instaparse I'll re-open though until we figure out what's going on.

**Comment by norton-at-kpmg** [comment]
Thank you.

I installed instaparse locally and then ran lein test for instacheck.

`FAIL in (parse-test) (core_test.clj:133)
error throwing parser
expected: (thrown? Exception (core/parse p5 "abc"))
  actual: nil
`

This is unrelated but thought I would share this.  Thank you.
